### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Edsonromeumaier** [morgannadev/octocats_da_comunidade#35]
@morgannadev , por favorcoloque meu nome na issue.

**Comment by morgannadev** [comment]
Olá, @Edsonromeumaier! Ainda tem interesse em prosseguir com essa issue? Qualquer dúvida, só chamar!

**Comment by Edsonromeumaier** [comment]
Ola, Moga!
Desculpe, ainda sou bem iniciante nestas questões ainda e fiquei um pouco
perdido.
então eu devo fechar a issue, né? tenho que fazer comentário?
Na verdade eu estava primeiramente querendo participar de fato de algum
projeto. Mas na minha primeira olhada
 os projetos fogem das minhas habilidades técnicas. Mas tenho interesse
total e também tenho tempo. Logo vou conseguir colaborar.
Obrigado pela paciência. Abraços

Em qua., 18 de out. de 2023 às 21:19, Morganna ***@***.***>
escreveu:
