### ISSUE TITLE
Adicionar Octocat de Juliana Conde

### ISSUE THREAD

**Issue by julianaconde** [morgannadev/octocats_da_comunidade#6]
Olá, @morgannadev! Você pode atribuir a mim esta issue? Obrigada!

**Comment by morgannadev** [comment]
Olá, @julianaconde! Ainda tem interesse em prosseguir com essa issue? Qualquer dúvida, só chamar!

**Comment by julianaconde** [comment]
@morgannadev  tenho sim! Enviei o commit com minha Octocat. Coloquei o "close e o numero da issue" pra fechar automaticamente como estava nas orientações. Será q fiz algo errado ou faltou alguma coisa?

**Comment by morgannadev** [comment]
@julianaconde talvez você tenha atualizado só no seu repositório. Agora você precisa abrir uma Pull Request para o meu repositório. Assim ele vai atualizar aqui também, depois de aprovarmos o PR.

Fui olhar o seu repositório e nele tem a seguinte mensagem:
> This branch is [1 commit ahead](https://github.com/julianaconde/octocats_da_comunidade/compare/morgannadev:octocats_da_comunidade:main...main), [70 commits behind](https://github.com/julianaconde/octocats_da_comunidade/compare/main...morgannadev:octocats_da_comunidade:main) morgannadev:main.

![print conforme descriçãõ acima](https://github.com/morgannadev/octocats_da_comunidade/assets/19210643/7ef057c3-e388-4b13-9daf-3c6f97c45cde)

Bem em cima da lista de arquivos, quase no meio da página. Talvez nessa mensagem para você, apareça um botão "contribuir" ou "contribute". Você deverá clicar ali para criar a PR.

Veja se consegue identificar e fazer isso. Se não conseguir, vai me avisando que vou tentando te ajudar!

**Comment by julianaconde** [comment]
@morgannadev Ah! Agora eu vi que não foi mesmo. Consegui enviar. Você pode verificar se deu certo, por favor?

**Comment by morgannadev** [comment]
@julianaconde recebi certinho sim, só te pedi uma coisinha lá no PR. Qualquer dúvida, me fala!

**Comment by julianaconde** [comment]
Não estou encontrando. Procurei a PR lá e não vi comentários novos. Aonde consigo acessar?
